In [2]:
import json
import pandas as pd

### Combine the data into three files

In [3]:
def concat_json_files(file1, file2, file3, output_file):
    data = []
    
    for file in [file1, file2, file3]:
        with open(file, 'r', encoding='utf-8') as f:
            data.extend(json.load(f))  # Assuming JSON files contain lists
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

# Example usage
concat_json_files('real_state_en.json', 'registration_en.json', 'laws_en.json', 'data_en.json')
concat_json_files('real_state_fr.json', 'registration_fr.json', 'laws_fr.json', 'data_fr.json')
concat_json_files('real_state_ar.json', 'registration_ar.json', 'laws_ar.json', 'data_ar.json')

## Changing data format

In [4]:
def json_to_dataframe(file):
    with open(file, 'r', encoding='utf-8') as file:
        data = json.load(file)
    # Convert to DataFrame
    df = pd.DataFrame(data)
    return df

In [5]:
df_en=json_to_dataframe('data_en.json')
df_en.head()

,section,question,subtopic,answer
0,Real Estate,Why Investing In Real Estate In Tunisia? A Pro...,intrdocution,Investing in homes for personal or family use ...
1,Real Estate,Why Investing In Real Estate In Tunisia? A Pro...,Economic Growth And Stability,"[Tunisia boasts a growing economy, offering a ..."
2,Real Estate,Why Investing In Real Estate In Tunisia? A Pro...,Increasing Demand For Housing,[With a rising population and rapid urbanizati...
3,Real Estate,Why Investing In Real Estate In Tunisia? A Pro...,Opportunities In Tourism,[Tunisia’s booming tourism sector drives stron...
4,Real Estate,Why Investing In Real Estate In Tunisia? A Pro...,Favorable Regulatory Environment,[The Tunisian government encourages foreign in...

In [6]:
df_fr=json_to_dataframe('data_fr.json')
df_fr.head()

,section,question,subtopic,answer
0,Real Estate,Pourquoi Investir Dans L’Immobilier En Tunisie...,intrdocution,Investir dans des maisons à usage personnel ou...
1,Real Estate,Pourquoi Investir Dans L’Immobilier En Tunisie...,Croissance Et StabilitÉ ÉConomiques,[La Tunisie bénéficie d’une économie en croiss...
2,Real Estate,Pourquoi Investir Dans L’Immobilier En Tunisie...,Demande Croissante De Logements,[Avec une population croissante et une urbanis...
3,Real Estate,Pourquoi Investir Dans L’Immobilier En Tunisie...,OpportunitÉS Dans Le Tourisme,[Le secteur touristique en plein essor en Tuni...
4,Real Estate,Pourquoi Investir Dans L’Immobilier En Tunisie...,Environnement RÉGlementaire Favorable,[Le gouvernement tunisien encourage l’investis...

In [7]:
df_ar=json_to_dataframe('data_ar.json')
df_ar.head()

,section,question,subtopic,answer
0,Real Estate,لماذا الاستثمار في العقارات في تونس؟ فرصة واعدة,intrdocution,يعد الاستثمار في المنازل للاستخدام الشخصي أو ا...
1,Real Estate,لماذا الاستثمار في العقارات في تونس؟ فرصة واعدة,النمو الاقتصادي والاستقرار,[تتمتع تونس باقتصاد متنامٍ، وتوفر بيئة مواتية ...
2,Real Estate,لماذا الاستثمار في العقارات في تونس؟ فرصة واعدة,تزايد الطلب على السكن,[مع ارتفاع عدد السكان والتوسع الحضري السريع، ي...
3,Real Estate,لماذا الاستثمار في العقارات في تونس؟ فرصة واعدة,الفرص المتاحة في السياحة,[يساهم قطاع السياحة المزدهر في تونس في تعزيز ا...
4,Real Estate,لماذا الاستثمار في العقارات في تونس؟ فرصة واعدة,بيئة تنظيمية مواتية,[تشجع الحكومة التونسية الاستثمار الأجنبي، وتسه...

In [8]:
def format_answer(group):
    combined = []
    for index, row in group.iterrows():
        combined.append(f"{row['subtopic']}:\n- {row['answer']}")
    return '\n\n'.join(combined)

In [9]:
columns_order=['section','question','answer']

In [10]:
data_en_grouped = df_en.groupby(['question', 'section']).apply(format_answer).reset_index(name='answer')
data_en_grouped = data_en_grouped[columns_order]
data_en_grouped.head()

C:\Users\MSI\AppData\Local\Temp\ipykernel_11380\2371065696.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_en_grouped = df_en.groupby(['question', 'section']).apply(format_answer).reset_index(name='answer')

,section,question,answer
0,Real Estate,10 Expert Recommendations For Maximizing The P...,"intrdocution:\n- In this article, we unveil th..."
1,Real Estate,10 Steps For A Successful Home Purchase In Tun...,intrdocution:\n- Congratulations! Purchasing a...
2,Real Estate,37 Key Questions To Ask When Purchasing A Hous...,"intrdocution:\n- To start, there are no foolis..."
3,Real Estate,5 Key Questions To Ask When Buying A Property ...,intrdocution:\n- Whether you are a seasoned in...
4,Real Estate,5 Practical Tips To Reduce Your Carbon Footpri...,intrdocution:\n- While numerous factors remain...

In [11]:
data_ar_grouped = df_ar.groupby(['question', 'section']).apply(format_answer).reset_index(name='answer')
data_ar_grouped=data_ar_grouped[columns_order]
data_ar_grouped.head()

C:\Users\MSI\AppData\Local\Temp\ipykernel_11380\2583140696.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_ar_grouped = df_ar.groupby(['question', 'section']).apply(format_answer).reset_index(name='answer')

,section,question,answer
0,Real Estate,10 توصيات الخبراء لتعظيم إمكانات الفناء الخلفي...,intrdocution:\n- في هذه المقالة، نكشف النقاب ع...
1,Real Estate,10 خطوات لشراء منزل ناجح في تونس: دليلك الكامل,intrdocution:\n- تهانينا! يعد شراء منزل أحد أه...
2,Real Estate,37 سؤالًا أساسيًا يجب طرحها عند شراء منزل في ت...,intrdocution:\n- للبدء، لا توجد أسئلة حمقاء يم...
3,Real Estate,5 أسئلة أساسية يجب طرحها عند شراء عقار في المرسى,intrdocution:\n- سواء كنت مستثمرًا متمرسًا أو ...
4,Real Estate,5 استراتيجيات لتوليد الدخل السلبي من خلال الاس...,intrdocution:\n- واحدة من المزايا العديدة كسب ...

In [12]:
data_fr_grouped = df_fr.groupby(['question', 'section']).apply(format_answer).reset_index(name='answer')
data_fr_grouped=data_fr_grouped[columns_order]
data_fr_grouped.head()

C:\Users\MSI\AppData\Local\Temp\ipykernel_11380\218180285.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_fr_grouped = df_fr.groupby(['question', 'section']).apply(format_answer).reset_index(name='answer')

,section,question,answer
0,Real Estate,10 Recommandations D'Experts Pour Maximiser Le...,"intrdocution:\n- Dans cet article, nous dévoil..."
1,Real Estate,10 ÉTapes Pour RÉUssir Votre Achat Immobilier ...,intrdocution:\n- Félicitations! L’achat d’une ...
2,Real Estate,37 Questions ClÉS À Poser Lors De L'Achat D'Un...,"intrdocution:\n- Pour commencer, il n’y a pas ..."
3,Real Estate,5 Conseils Pratiques Pour RÉDuire Votre Emprei...,intrdocution:\n- Si de nombreux facteurs échap...
4,Real Estate,5 Questions ClÉS À Poser Lors De L'Achat D'Un ...,intrdocution:\n- Que vous soyez un investisseu...

In [14]:
# Convert DataFrames to JSON strings with special characters preserved
data_en_json = data_en_grouped.to_dict(orient='records')
data_fr_json = data_fr_grouped.to_dict(orient='records')
data_ar_json = data_ar_grouped.to_dict(orient='records')
with open('data_en.json', 'w', encoding='utf-8') as f:
    json.dump(data_en_json, f, ensure_ascii=False, indent=4)

with open('data_fr.json', 'w', encoding='utf-8') as f:
    json.dump(data_fr_json, f, ensure_ascii=False, indent=4)

with open('data_ar.json', 'w', encoding='utf-8') as f:
    json.dump(data_ar_json,f,ensure_ascii=False,indent=4)